### ISSUE TITLE
Threshold doesn't update from Classification Algorithm

### ISSUE THREAD

**Issue by ynobu14001** [semiautomaticgit/SemiAutomaticClassificationPlugin#10]
I tried SCP5.02, then I found that the error which I reported was fixed.
Veeeeery Thanks to your quick work !!

Sorry bother you.  I found another error  again.

When I changed threshold in doc of Classification Algorithm, but it didn't update.
Using signature threshold tab in tools window, I could update it.

If you know please disregard...

**Comment by semiautomaticgit** [comment]
You are welcome.
What you described I think it is OK.
Threshold should be set using the threshold tab. The threshold in the Classification Algorithm is applied when you save a new ROI (so you don't lose the threshold values for previously saved ROIs).
If your issue is different, please provide further details.

**Comment by ynobu14001** [comment]
Thank you very much. I tried below and it worked well !!
> so you don't lose the threshold values for previously saved ROIs

**Comment by semiautomaticgit** [comment]
You are very welcome. I am glad it worked.
Also, for classifications you should check MC ID or C ID according to your needs..
