### ISSUE TITLE
QGIS 3.14 crashed when uninstalling

### ISSUE THREAD

**Issue by aticup** [semiautomaticgit/SemiAutomaticClassificationPlugin#115]
I have tried to uninstall the plugin before on QGIS 3.12 as well but everytime I do this, QGIS crashes.

**Comment by Evanilton** [comment]
I have the same problem with the constant crashing. However, I managed to somehow revert to 3.12 (which I don't remember how It did so and would like to do it again) and it worked as nicely as always and allowed me to uninstall it. Then, updated again to 3.14 and kept working neatly until (by my mistake) I installed the plugin again.

**Comment by Evanilton** [comment]
Hi
I uninstalled 3.14 altogether and made an express installation. The OSGeo4W setup installed the 3.12 version and is working properly with the plugin.
I suggest, if 3.12 is not working, to install a 3.10 form a standalone and try to remove the plugin. Then update to 3.12 and use it while awaiting a fix for 3.14.15

**Comment by semiautomaticgit** [comment]
Hi, thank you for your feedbacks.

Unfortunately the SCP dependency SciPy is broken in QGIS. It is related to this QGIS issue https://github.com/qgis/QGIS/issues/38372 .

I've fixed the QGIS crash in SCP 6.4.7, but of course the functions requiring SciPy won't work.
In order to use all the tools of SCP, until they fix the SciPy issue, you should install the QGIS version 3.10.8 or previous.



> I have tried to uninstall the plugin before on QGIS 3.12 as well but everytime I do this, QGIS crashes.

In case it happens in the future, you could manually remove the SCP directory in the QGIS plugin folder
