### ISSUE TITLE
SACP blocks Georeferencer in MacOS version of QGIS

### ISSUE THREAD

**Issue by Spartacus1** [semiautomaticgit/SemiAutomaticClassificationPlugin#189]
If SACP is installed, the QGIS included GDAL Georeferencer (available from Raster->Georeferencer), will not work and will crash QGIS (will hang when the progress bar appears). The only way to make it work again is to uninstall SACP completely. 
Cheers

**Comment by mbodnar-GS** [comment]
This is also the case on Windows 10 installations, SCP must be disabled to use the Georeferencer. This appears to be something that occurs when QGIS starts and the plugin is initialized as there is a "threadsValue" line that is placed in the QGIS.ini file at start-up. A github member called 'RinceWND' described this behavior in the QGIS page.

https://github.com/qgis/QGIS/issues/46327

**Comment by RinceWND** [comment]
@mbodnar-GS Thank you for referencing the issue here!

I believe the culprit is the `GDAL_NUM_THREADS` option that is set here: https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/blob/3e7c9f43a152b00c9ce697f783b9f602052a0383/semiautomaticclassificationplugin.py#L428
Seems like these settings are global for QGIS, and GDAL's `ChunkAndWarpImage` function doesn't like this specific one.

**Comment by semiautomaticgit** [comment]
Hello and thank you @mbodnar-GS and @RinceWND . 
It is a really strange issue. I'll try to fix this from the SCP side.
As a workaround for using the Georeferencer, I recommend disabling SCP temporary.

**Comment by Spartacus1** [comment]
I'm already doing the temporary disable trick. Hope this is a simple one to fix.

**Comment by RinceWND** [comment]
The funny thing is that I can't seem to reproduce the issue on an Ubuntu machine with QGIS (3.22, which I believe is installed from ppa)... The georeferencer works flawlessly regardless of the plugin's threads number value.
On my Windows machine I just left CPU threads value to 1 as a workaround which works for me.

**Comment by roya0045** [comment]
Possibly triggering this bug https://github.com/qgis/QGIS/issues/41770

An option would be to increase the number of threads for operations that would benefit from it and the setting the number back to one. Or make the feedback handle the multithread in the georeferencer.

**Comment by mc-geo-rs** [comment]
I experienced this issue on Windows 10 using QGIS 3.22.0, disabling the SCP plugin and restarting QGIS fixed the issue. Posting so others like me who came from Google will know of the temporary fix.

**Comment by agiudiceandrea** [comment]
This is the root cause of the issue reported at: https://github.com/qgis/QGIS/issues/46327.
Possibly triggering also this issue: https://github.com/qgis/QGIS/issues/50107.
@semiautomaticgit, are you looking at way to fix this issue?

**Comment by semiautomaticgit** [comment]
Thank you for your feedback.
I have changed the behavior of the SCP in version 7.10.7 to avoid the triggering of this issue.

To be clear, the Georeferencer plugin issue is not caused by the SCP.
The SCP sets the GDAL configuration option GDAL_NUM_THREADS.
The Georeferencer plugin has issues if this option GDAL_NUM_THREADS is greater than 1.
Georeferencer plugin developers may have to fix this issue, because other plugins or users could change this option and trigger the issue in the future.
