### ISSUE TITLE
SCP main menu window not automatically showing on the foreground

### ISSUE THREAD

**Issue by GITHUBAntoineDENIS** [semiautomaticgit/SemiAutomaticClassificationPlugin#250]
Hello Lucas,
When using SCP, and the main menu window (confer image) (semi-automatic classification plugin window), this window, if already opened previously, will not appear/show on the foreground when clicking on a function available in the main scp menu (confer image). And so we have rather to recall that scp window by clicking on that window in the bottom windows taskbar to mak it appear on the foreground. It would be much nicer if that scp window could show on the foreground when clicking on a function available in the main menu. Or else we have the impression that nothing happen, and students are confused all the time until they understand they have to recall the window from the task bar. 
Best regards,
Antoine 

![image](https://user-images.githubusercontent.com/44610746/208066819-bd51f3a5-3196-48d8-80ba-cd337fcb04c2.png)

![image](https://user-images.githubusercontent.com/44610746/208066349-328b54e4-8626-4362-bef8-0e86d709bc31.png)
![image](https://user-images.githubusercontent.com/44610746/208067055-7b816d34-6ac2-4a51-b3d0-f988257d9f98.png)

**Comment by semiautomaticgit** [comment]
Hello @GITHUBAntoineDENIS , thank you for opening this.
Unfortunately I don't think I can fix this, because actually the plugin already tries to bring the window on top (it works on other operating systems). But on Windows, if the windows was minimized it doesn't bring the window on top. At the moment I don't know about workarounds.
