### ISSUE TITLE
Error [40]: Unable to connect with L8 OLI/TIRS

### ISSUE THREAD

**Issue by Xarre90** [semiautomaticgit/SemiAutomaticClassificationPlugin#37]
If i want to preview the landsat image, then there is an error "Error [40]: Unable to connect" 

It's possible to find the images and it's possible to download them (when the button "only if preview in Layers" is off. But it's NOT possible to preview them "Error [40]: Unable to connect"

**Comment by semiautomaticgit** [comment]
Hello and thank you for opening this.

This seems an error caused by changes of the Landsat Collection 1 preview url  in the site earthexplorer.usgs.gov .
The search queries to Earthdata earthdata.nasa.gov still return the old urls, causing this issue. 
I hope that they will fix this soon, but at the moment the Landsat previews aren't available in SCP, therefore the only solution to download Landsat images is to disable the option "only if preview in Layers" .

**Comment by semiautomaticgit** [comment]
This has been fixed
