### ISSUE TITLE
Error opening Plugin

### ISSUE THREAD

**Issue by eamanu** [semiautomaticgit/SemiAutomaticClassificationPlugin#79]
Hello,

I install the plugin using the QGis manger plugin. But when I click over SemiAutomaticClassificationPlugin on manager plugin after install I have the next error:

```
QGIS died on signal 11Aborted
```
I am using:

```
QGIS 3.10.1-A Coruña 'A Coruña' (ef24c526da)
```

**Comment by semiautomaticgit** [comment]
Hello,
it seems an installation issue.
What operating system are you using?
Please try to reinstall QGIS.

**Comment by eamanu** [comment]
Hi, thanks for your response. This is embarrassing, I didn't see the 

```sudo apt-get install qgis python3-matplotlib python3-scipy ```

on tutorial.

Sorry for the noise. I closed this issue. But I have other question, I need run the pluggin via command line, theare any chance to do that?

Thanks!

**Comment by semiautomaticgit** [comment]
Hello, thank you for your feedback.
Unfortunately it is not possible to run from command line, however you can use Batch tool for automatic execution 
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/main_interface_window.html#batch

**Comment by RohitDhankar** [comment]
@semiautomaticgit , thanks for the wonderful plugin . Am aware that this issue is closed . Dont want to create another issue - am sure im missing something very basic here - your help highly appreciated . 

**My issue** - the plugin doesnt seem to find the installed ```python3-scipy```. 

**QGIS Version** - 3.12 Bucuresti

Terminal Print in UBUNTU - 
`QGIS died on signal 11Could not attach to process.  If your uid matches the uid of the target process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf ptrace: Operation not permitted. No thread selected No stack. gdb returned 0 Aborted (core dumped)`

Have installed - ```python3-matplotlib python3-scipy python3-numpy```

![Screenshot from 2020-07-10 21-01-47](https://user-images.githubusercontent.com/13214169/87171649-97075080-c2f0-11ea-8b40-a39133dc800a.png)


Screencaptures of the QGIS UI as below - 

![Screenshot from 2020-07-10 20-50-10](https://user-images.githubusercontent.com/13214169/87170920-9d48fd00-c2ef-11ea-9ae9-7f054d4542b5.png)
![Screenshot from 2020-07-10 20-50-07](https://user-images.githubusercontent.com/13214169/87170945-a5a13800-c2ef-11ea-8a3d-3808e1a3f065.png)
