### ISSUE TITLE
Sentinel-2 bands don't open

### ISSUE THREAD

**Issue by margeorita** [semiautomaticgit/SemiAutomaticClassificationPlugin#86]
I have some downloaded images from Sentinel-2. But plugin does't want to open their bands, so I can't preprocess it. What should I do?
![image](https://user-images.githubusercontent.com/53615462/76390956-6b467f00-637f-11ea-9da0-312c67231802.png)

And there are not any errors
![image](https://user-images.githubusercontent.com/53615462/76390406-66350000-637e-11ea-90fc-6eba32107138.png)

**Comment by semiautomaticgit** [comment]
Hello, the plugin can only open the directory containing the .jp2 files, so you should move all the images in one directory

**Comment by LuminousLizard** [comment]
Btw .... the "Preprocessing > Sentinel-2" tab has also a problem with the image names of manually downloaded images: The images are also not loaded if the file name contains the wavelength.

E.g. after clipping I have the file "clip_T32UPA_20210923T102031_B04_10m.tif" inside the directory, but this file will NOT load in the preprocessing tab.

But If I remove the wavelength from the filename (clip_T32UPA_20210923T102031_B04.tif) then the files are loaded.

**Comment by semiautomaticgit** [comment]
> But If I remove the wavelength from the filename (clip_T32UPA_20210923T102031_B04.tif) then the files are loaded.

Hello @LuminousLizard , the plugin can detect the band number only if the file name ends with the band number.
Because manually downloaded bands have name ending with the spatial resolution (e.g. 10m, 20m), it is not possible to detect the band number. In fact, bands downloaded through the plugin are automatically renamed.
For manually downloaded images, the only solution is to rename the file names.
